ProyectoFinal/miscosas/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index),
    path('alimentadores', views.alimentadores),
    path('alimentadores/add', views.add_content),
    path('alimentadores/<str:feeder>', views.pagina_alimentador),
    path('alimentadores/<str:feeder>/<str:id>', views.pagina_item),
    path('alimentadores/<str:feeder>/<str:id>/vote', views.vote),
    path('usuarios', views.usuarios),
    path('usuarios/<str:username>', views.usuario),
    path('usuarios/<str:username>/image', views.changeImage),
    path('informacion', views.informacion),
    path('loggedIn', views.loggedIn),
    path('logout', views.logoutView),
    path('register', views.register),
    path('i18n/', include('django.conf.urls.i18n')),
]

ProyectoFinal/proyecto/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView as login
from miscosas import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('miscosas.urls')),
    path('admin', admin.site.urls),
    path('login', login.as_view()),
    path('register', views.register),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoFinal/miscosas/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

class Alimentador(models.Model):
    id = models.CharField(max_length=64, primary_key=True)
    titulo = models.CharField(max_length=64, null=True, blank=False)
    link = models.CharField(max_length=64, null=True, blank=False)
    num_items = models.IntegerField(default=0)
    puntuacion = models.IntegerField(default=0)
    elegido = models.BooleanField(default=True)

    def __str__(self):
        return self.titulo

    def es_wikipedia(self):
        return ('Revision history' in self.titulo)

class Item(models.Model):
    alimentador = models.ForeignKey(Alimentador, on_delete=models.CASCADE, null=True)
    titulo = models.CharField(max_length=64, null=True)
    link = models.CharField(max_length=64, null=True)
    id = models.CharField(max_length=64, primary_key=True)
    descripcion = models.CharField(max_length=1024, null=True)
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    puntuacion = models.IntegerField(default=0)

    def __str__(self):
        return self.titulo

class Voto(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    voto = models.IntegerField(default=0)

    def __str__(self):
        if self.voto < 0:
            return self.user.username + " ha dado dislike"
        else:
            return self.user.username + " ha dado like"

class Comentario(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=64, null=True)
    comentario = models.CharField(max_length=256, null=True)
    fecha = models.DateTimeField(default=datetime.now, blank=True)
    imagen = models.ImageField(blank=True, null=True, upload_to="miscosas")

    def __str__(self):
        return self.user.username + " comenta " + self.comentario + " | " + self.item.titulo

class Imagen(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null = True)
    imagen = models.ImageField(default="default.png", upload_to="miscosas")

    def __str__(self):
        return self.imagen.name

class Opciones(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    MODO = (('L', 'Ligero'), ('O', 'Oscuro'),)
    modo = models.CharField(max_length=1, choices=MODO, default='Ligero',
            help_text='Modo de color para la página')
    SIZE = (('P', 'Pequeña'), ('M', 'Mediana'),('G', 'Grande'),)
    size = models.CharField(max_length=1, choices=SIZE, default='M',
            help_text='Tamaño de la letra')

    def __str__(self):
        return self.user.username + " " + self.modo + " " + self.size

ProyectoFinal/miscosas/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Alimentador, Comentario, Imagen, Opciones

class LoginForm(forms.Form):

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class ComentarioForm(forms.ModelForm):

    class Meta:
        model = Comentario
        fields = ('titulo', 'comentario', 'imagen')

class ImagenForm(forms.ModelForm):

    class Meta:
        model = Imagen
        fields = ['imagen',]

ProyectoFinal/miscosas/views.py
from django.shortcuts import render, redirect, get_object_or_404, render
from .forms import LoginForm, ComentarioForm, ImagenForm
from .models import Alimentador, Item, Voto, Comentario, Imagen, Opciones
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.template.loader import get_template
from django.template import Context, RequestContext
from .ytchannel import YTChannel
from .wikipage import WikiArticle
import urllib
import json
from django.core import serializers
from django.forms.models import model_to_dict
import xml.etree.cElementTree as ET
from django.conf import settings
from django.utils import translation
from django.utils.translation import gettext as _
from django.utils.translation import check_for_language

def set_language(request):
    language = request.POST.get('language', settings.LANGUAGE_CODE)
    cur_language = translation.get_language()
    try:
        translation.activate(language)
        text = translation.gettext('Cambie el idioma')
    finally:
        translation.activate(cur_language)
        text = translation.gettext('Cambie el idioma')
    return redirect('/')

def seleccionar(request):
    if request.method == 'POST':
        action = request.POST['Select']
        id = request.POST['id']
        if id != "":
            alimentador = get_object_or_404(Alimentador, id=id)
            if action == 'Elegir' or action == 'Select':
                alimentador.elegido = True
                if alimentador.es_wikipedia():
                    nombre = id.split()[0]
                    url = "https://en.wikipedia.org/w/index.php?title=" + nombre + "&action=history&feed=rss"
                    xmlStream = urllib.request.urlopen(url)
                    articulo = WikiArticle(xmlStream)
                    articulo = Alimentador.objects.get(titulo=id)
                    items = Item.objects.filter(alimentador=articulo)
                    alimentador.num_items = len(items)
                    alimentador.save()
                    redirect = '/alimentadores/' + str(alimentador.titulo)
                else:
                    url = "https://www.youtube.com/feeds/videos.xml?channel_id=" + id
                    xmlStream = urllib.request.urlopen(url)
                    canal = YTChannel(xmlStream)
                    canal = Alimentador.objects.get(id=id) 
                    items = Item.objects.filter(alimentador=canal)
                    alimentador.num_items = len(items)
                    alimentador.save()
                    redirect = '/alimentadores/' + str(alimentador.titulo)
            elif action == 'Eliminar' or action == 'Delete':
                alimentador.elegido = False
                alimentador.save()
                redirect = '/'
            return redirect

def barraxml(user):
    template = get_template("main.xml")
    alimentadores = Alimentador.objects.filter(elegido=True)
    items = Item.objects.order_by('-puntuacion')[:10]
    c = RequestContext(user, {"alimentadores" : alimentadores, "items" : items}).flatten()
    if user.is_authenticated:
        lastvoted = Voto.objects.filter(user=user)[:5]
        c = RequestContext(user, {"user":user,"alimentadores" : alimentadores, "items" : items, "voteditems":lastvoted}).flatten()
    respuesta = template.render(c)
    return HttpResponse(respuesta, status=200, content_type="application/xml")

def barrajson(user):
    all = [*Alimentador.objects.filter(elegido=True), *Item.objects.order_by('-puntuacion')[:10]]
    indexjson = serializers.serialize('json', all)
    if user.is_authenticated:
        all = [*Alimentador.objects.filter(elegido=True), *Item.objects.order_by('-puntuacion')[:10], *Voto.objects.filter(user=user)[:5]]
        indexjson = serializers.serialize('json', all)
    return indexjson

def index(request):

    set_language(request)
    if request.method == "GET":
        formato = request.GET.get('format')
        if formato:
            if formato == 'xml':
                return HttpResponse(barraxml(request.user), status=200, content_type="application/xml")
            else:
                return HttpResponse(barrajson(request.user), status=200, content_type="application/json")
    if seleccionar(request) != None:
        return redirect(seleccionar(request))
    canales = []
    articulos = []
    alimentadores = Alimentador.objects.filter(elegido=True)
    for alimentador in alimentadores:
        if not alimentador.es_wikipedia():
            canales.append(alimentador)
        else:
            articulos.append(alimentador)
    items = Item.objects.order_by('-puntuacion')[:10]
    context = {'alimentadores': alimentadores,'canales':canales,'articulos':articulos,'items': items}
    if request.user.is_authenticated:
        user = request.user
        itemsvotados = []
        votos = Voto.objects.filter(user=user)
        for voto in votos:
            itemsvotados.append(voto.item)
        lastvoted = votos[:5]
        imagenusuario = Imagen.objects.get(user=user)
        opciones = Opciones.objects.get(user=user)
        context = {"imagenusuario":imagenusuario, "opciones":opciones, "alimentadores":alimentadores,
                    "canales":canales, "articulos":articulos, 'items': items,'lastvoted': lastvoted, 
                    'votos': votos, 'itemsvotados':itemsvotados, 'user': user}

    return render(request, "index.html", context)

def alimentadores(request):

    if seleccionar(request) != None:
        return redirect(seleccionar(request))
    canales = []
    articulos = []
    alimentadores = Alimentador.objects.all()
    for alimentador in alimentadores:
        if not alimentador.es_wikipedia():
            canales.append(alimentador)
        else:
            articulos.append(alimentador)

    context = {"alimentadores":alimentadores,"canales":canales, "articulos":articulos}
    user = request.user
    if user.is_authenticated:
        opciones = Opciones.objects.get(user=user)
        imagenusuario = Imagen.objects.get(user=user)
        context = {"opciones":opciones, "alimentadores":alimentadores,"canales":canales, "articulos":articulos,"imagenusuario":imagenusuario} 
    return render(request, 'alimentadores.html', context)

def add_content(request):
    id = ""
    nombre_articulo = ""
    if request.method == 'POST':
        try:
            nombre_articulo = request.POST['articulo']
        except:
            id = request.POST['id']
            if id == "":
                return HttpResponse("Inserte el nombre del contenido")
        if id == "":
            titulo = str(nombre_articulo) + " - Revision history"
            url = "https://en.wikipedia.org/w/index.php?title=" + nombre_articulo + "&action=history&feed=rss"
            xmlStream = urllib.request.urlopen(url)
            articulo = WikiArticle(xmlStream)
            articulo = Alimentador.objects.get(titulo=titulo)
            items = Item.objects.filter(alimentador=articulo)
            articulo.num_items = len(items)
            articulo.elegido = True
            articulo.save()
            url = '/alimentadores/' + titulo
        elif nombre_articulo == "":
            url = "https://www.youtube.com/feeds/videos.xml?channel_id=" + id
            xmlStream = urllib.request.urlopen(url)
            canal = YTChannel(xmlStream)
            canal = Alimentador.objects.get(id=id) 
            items = Item.objects.filter(alimentador=canal)
            canal.num_items = len(items)
            canal.elegido = True
            canal.save()
            url = '/alimentadores/' + str(canal.titulo)
        return redirect(url)

def usuario(request, username):

    try:
        user = request.user
        userpage = User.objects.get(username=username)
        if user.is_authenticated:
            opciones = Opciones(user=user)
            size = Opciones
            if request.method == "POST" and user == userpage:
                action = request.POST['Ajustar']
                if action == "Mediana" or action == "Medium":
                    opciones = Opciones.objects.filter(user=user).update(size="M")

                if action == "Pequeña" or action == "Small":
                    opciones = Opciones.objects.filter(user=user).update(size="P")

                if action == "Grande" or action == "Big":
                    opciones = Opciones.objects.filter(user=user).update(size="G")

                if action == "Oscuro" or action == "Dark":
                    opciones = Opciones.objects.filter(user=user).update(modo="O")

                if action == "Ligero" or action == "Light":
                    opciones = Opciones.objects.filter(user=user).update(modo="L")
        try:
            imagen = Imagen.objects.get(user=userpage)
        except Imagen.DoesNotExist:
            pass 
        votos = Voto.objects.filter(user=userpage)
        comentarios = Comentario.objects.filter(user=userpage)

        context = {"user":user,"userpage":userpage,"votos":votos,"comentarios":comentarios,"imagen":imagen}
        
        if user.is_authenticated:
            opciones = Opciones.objects.get(user=user)
            imagenusuario = Imagen.objects.get(user=user)
            context = {"user":user, "opciones":opciones, "userpage": userpage,"votos":votos, "comentarios":comentarios, 
                        "imagen":imagen, "imagenusuario":imagenusuario}
        return render(request, "usuario.html", context)
    
    except User.DoesNotExist:
        return HttpResponse("Usuario no encontrado")

def usuarios(request):

    users = User.objects.all()
    votos = Voto.objects.all()
    comentarios = Comentario.objects.all()
    imagenes = Imagen.objects.all()
    alimentadores = Alimentador.objects.all()

    context = {"alimentadores":alimentadores,"users":users,"votos":votos,"comentarios":comentarios,"imagenes":imagenes}
    user = request.user

ProyectoFinal/miscosas/templates/alimentador.html
{% extends "base.html" %}
{% load i18n %}

{% block alimentador %}
    {% if not alimentador.es_wikipedia %}
        <h2>{{ alimentador.titulo }}</h2>
        {% trans "Enlace del canal" %}: <a href='{{ alimentador.link }}'>{{alimentador.titulo}}</a><br>
        {% trans "Número de vídeos" %}: {{ alimentador.num_items }}<br>
        {% trans "Puntuación" %}: {{ alimentador.puntuacion }}<br><br>
        {% trans "Lista de videos" %}:<br>
        {% for item in items %}
    	    <li>{% trans "Título" %}:
    	        <a href='/alimentadores/{{alimentador.titulo}}/{{item.id}}'>{{item}}</a><br>
    	        Link: <a href='{{item.link}}'>{{item.link}}</a><br>
    	    </li>
        {% endfor %}
    {% else %}
        <h2>{{ alimentador.titulo }}</h2>
        {% trans "Enlace del artículo" %}: <a href='{{ alimentador.link }}'>{{alimentador.titulo}}</a><br>
        {% trans "Número de cambios" %}: {{ alimentador.num_items }}<br>
        {% trans "Puntuación" %}: {{ alimentador.puntuacion }}<br><br>
        {% trans "Lista de revisiones" %}:<br>
        {% for item in items %}
            <li>{% trans "Título" %}:
                <a href='/alimentadores/{{alimentador.titulo}}/{{item.id}}'>{{item.id}}</a><br>
                Link: <a href='{{item.link}}'>{{item.link}}</a><br>
            </li>
        {% endfor %}
    {% endif %}
{% endblock %}

ProyectoFinal/miscosas/templates/alimentadores.html
{% extends "base.html" %}
{% load i18n %}

{% block alimentadores %}
	<h1>{% trans "Alimentadores de Youtube" %}</h1>
      {% for canal in canales %}
          <h2>{{canal.titulo}}</h2>
          <li>{% trans "Título" %}:
          <a href='/alimentadores/{{canal.titulo}}'>{{canal.titulo}}</a></li><br>
            {% trans "Enlace del canal" %}: <a href='{{ canal.link }}'>{{canal.titulo}}</a><br>
            {% trans "Número de vídeos" %}: {{ canal.num_items }}<br>
            {% trans "Puntuación" %}: {{ canal.puntuacion }}

          <form action="" method='POST'> 
            {% csrf_token %}
            <input type='hidden' name='id' value='{{canal.id}}'> 
            <input type='submit' name='Select' value='{% trans "Elegir" %}'>
            <input type='submit' name='Select' value='{% trans "Eliminar" %}'>
          </form>
          <br>
      {% endfor %}

    <h1>{% trans "Alimentadores de Wikipedia" %}</h1>
      {% for articulo in articulos %}
            <h2>{{articulo.titulo}}</h2>
            <li>{% trans "Título" %}:
            <a href='/alimentadores/{{articulo.titulo}}'>{{articulo.titulo}}</a></li><br>
              {% trans "Enlace del artículo" %}: <a href='{{ articulo.link }}'>{{articulo.titulo}}</a><br>
              {% trans "Número de artículos" %}: {{ articulo.num_items }}<br>
              {% trans "Puntuación" %}: {{ articulo.puntuacion }}
            <form action="" method='POST'> {% csrf_token %}
              <input type='hidden' name='id' value='{{articulo.id}}'> 
              <input type='submit' name='Select' value='{% trans "Elegir" %}'>
              <input type='submit' name='Select' value='{% trans "Eliminar" %}'>
            </form>
            <br>
      {% endfor %}
      
{% endblock %}

ProyectoFinal/miscosas/templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <link rel="shortcut icon" type="image/png" href={% static "favicon.ico" %}/>
        <title>MisCosasOnline</title>
		<link rel="stylesheet" href="{% static "bootstrap.css" %}" type="text/css">
		<link rel="stylesheet" href="{% static "main.css" %}" type="text/css">
    </head>
    <body>
        {% if opciones %}
            {% if opciones.modo == 'O' %}
                <link rel="stylesheet" href="{% static "oscuro.css" %}" type="text/css">
            {% endif %}

            {% if opciones.size == 'G' %}
                <link rel="stylesheet" href="{% static "grande.css" %}" type="text/css">
            {% elif opciones.size == 'P' %}
               <link rel="stylesheet" href="{% static "pequeña.css" %}" type="text/css">
            {% endif %}
        {% endif %}

        <div class="jumbotron text-center">
			<div class="row">

				<div class="col-sm-4">
					<div id="imagen"><img src="{% static "miscosaslogo.png" %}" alt="My image"></div>
		        </div>
	     
				<div class="col-sm-4">
					<div id="titulo">{% trans "Mis Cosas" %}</div>
		        	<div id="navegador">
			            <ul>
			            	{{ request.url }}
			            	{% if request.path != "/" %}
			                	<li><a href="/">{% trans "Inicio" %} </a></li>
			                {% endif %}
			                {% if request.path != "/alimentadores" %}
			                	<li><a href="/alimentadores">{% trans "Alimentadores" %} </a></li>
			                {% endif %}
			                {% if request.path != "/usuarios" %}
			                	<li><a href="/usuarios">{% trans "Usuarios" %} </a></li>
			                {% endif %}
			                {% if request.path != "/informacion" %}
			                	<li><a href="/informacion">{% trans "Información" %} </a></li>
			                {% endif %} 
			            </ul>
			        </div>	   
				</div>
				
				<div class="col-sm-4">

					<div id="LoginForm">
			            {% if user.is_authenticated %}
			                <h1>{% trans "Iniciado sesión como " %} {{ user.username }}</h1>
			                {% if imagenusuario %}
			                	<img src="{{ imagenusuario.imagen.url }}" width="90" height="90">
			                {% endif %}
			                <form class="button" action="/usuarios/{{user.username}}" method="GET">
			                    <input class="button" type="submit" value='{% trans "Perfil" %}'>
			                </form>
			                <form class="logout" action="/logout" method="POST">
			                    {% csrf_token %}
			                    <input class="button" type="submit" value='{% trans "Salir" %}'>
			                </form>
			            {% else %} 
			                <form class="login" action="/loggedIn" method="POST">
			                    {% csrf_token %}
			                    <table>
			                        <h1>{% trans "Inicie sesión" %}</h1>
			                        <tr>
			                            <td>{% trans "Usuario" %}</td>
			                            <td><input type="text" name="username" value="{{ form.username }}"></td>
			                        </tr><br>
			                        <tr>
			                            <td>{% trans "Contraseña" %}</td>
			                            <td><input type="password" name="password" value="{{ form.password }}"></td>
			                        </tr>
			                      </table>
			                    <input type="submit" value="{% trans "Iniciar sesión" %}"/>
			                </form> 
			                <form action="/register" method="GET">
			                    {% csrf_token %}
			                    <input class="button" type="submit" value="{% trans "Registrarse" %}">
			                </form>     
			            {% endif %}
		        	</div>
	        		<div id = "lenguage">
						<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
						    <input name="next" type="hidden" value="{{ redirect_to }}">
						    <select name="language">
						        {% get_current_language as LANGUAGE_CODE %}
						        {% get_available_languages as LANGUAGES %}
						        {% get_language_info_list for LANGUAGES as languages %}
						        {% for language in languages %}
						            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
						                {{ language.name_local }} ({{ language.code }})
						            </option>
						        {% endfor %}
						    </select>
						    <input type="submit" value="{% trans "ir" %}">
						</form>
					</div> 
		        </div>
		    </div>
		</div>
        

        <div class="container">
			<div class="row">
				<div class="col-sm-4">

					<div id="agregadores">
		            	<b>{% trans "Agregar contenido de YouTube" %}</b>
			            <form method="POST" action="/alimentadores/add">
			                {% csrf_token %}
			                <input type="text" name="id" placeholder='{% trans "ID del canal" %}' required=True>
			                <input type="submit" value='{% trans "Enviar" %}'>
			            </form>
			            <b>{% trans "Agregar contenido de Wikipedia" %}</b>
			            <form method="POST" action="/alimentadores/add">
			                {% csrf_token %}
			                <input type="text" name="articulo" placeholder='{% trans "Nombre artículo" %}' required=True>
			                <input type="submit" value ='{% trans "Enviar" %}'>
			            </form>
						{% block descarga %}
						{% endblock %}
						{% block indexalim %}
						{% endblock %}
				    </div>

			    </div>

				<div class="col-sm-8">

			        <div id="index">
			            {%block index %}
			            {% endblock %}
			        </div>

			        <div id="perfil">
			            {% block user %}
			            {% endblock %}
			        </div>

			        <div id="perfiles">
			            {% block users %}
			            {% endblock %}
			        </div>

			       	<div id = "imagen">
				        {% block imagen %}
				        {% endblock %}
				    </div>

			        <div id = "alimentador">
			        	{% block alimentador %}
			            {% endblock %}
			        </div>

			        <div id = "item">
			        	{% block item %}
			            {% endblock %}
			        </div>

			        <div id = "alimentadores">
			            {% block alimentadores %}
			            {% endblock %}
			        </div>

			        <div id = "informacion">
				        {% block informacion %}
				        {% endblock %}
				    </div>

		  			<div id="pie">
			            <br><h2>{% trans "Fuentes de contenido" %}</h2>
			            {% trans "Esta página web hace uso de contenidos de canales y videos Youtube, y los cambios en artículos de Wikipedia." %}
			        </div>
			    </div>
			</div>
		</div>
    </body>
</html>

ProyectoFinal/miscosas/templates/informacion.html
{% extends "base.html" %}
{% load i18n %}

{% block informacion %}
<div id="informacion">
	{% trans "Esta página web ha sido desarrollada por Daniel Rodríguez Población, alumno de Tecnologías de la Telecomunicación, y para la asignatura Servicios y Aplicaciones Telemáticas de la URJC. Este web busca almacenar contenidos de páginas como Youtube y Wikipedia, pudiendo registrarse como usuario y votando y comentando dichos contenidos.	Las fuentes de contenido importadas hacen referencia a las siguientes páginas" %}
	 <br> <br>
  	{% for alimentador in alimentadores %}
        {{ alimentador.titulo }}
        <a href='{{ alimentador.link }}'>{{alimentador.link}}</a><br>
    {% endfor %}
</div>
{% endblock %}

ProyectoFinal/miscosas/templates/item.html
{% extends "base.html" %}
{% load i18n %}

{% block item %}

	<h2> {{item}} </h2>
	<li>
		{% if not item.alimentador.es_wikipedia %}
			<br><b>{% trans "Vídeo" %}:</b> <a href='{{item.link}}'>{{item}}</a>
			<br><b>{% trans "Descripción" %}:</b> {{item.descripcion}}<br>
			<br><b>{% trans "Canal de YouTube" %}:</b> {{item.alimentador.titulo}}
			<br><b>{% trans "Link canal" %}:</b> <a href='{{item.alimentador.link}}'>{{item.link}}</a>
			<br>{% trans "Me gusta" %}: {{ item.likes }}
			<br>{% trans "No me gusta" %}: {{ item.dislikes }}
			<br><iframe width="560" height="315"
				src={{url}}
				frameborder="0"
				allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
				allowfullscreen>
			</iframe>
		{% else %}
			<br>{% trans "Titulo del cambio" %}: {{item}}
			<br>{% trans "Enlace" %}: <a href='{{item.link}}'>{{item.link}}</a>
			<br>{% trans "Fecha del cambio" %}: {{item.descripcion}}
			<br>{% trans "Nombre del artículo" %}: {{item.alimentador.titulo}}
			<br>{% trans "Link del árticulo" %}: <a href='{{item.alimentador.link}}'>{{item.alimentador.link}}</a>
			<br>{% trans "Me gusta" %}: {{ item.likes }}
			<br>{% trans "No me gusta" %}: {{ item.dislikes }}
		{% endif %}

		{% if user.is_authenticated %}
            <form method="POST" action="/alimentadores/{{item.alimentador.titulo}}/{{item.id}}/vote">
          		{% csrf_token %}
          		<li>{% trans "Puntúe" %}
	            	{% if voto.voto == 1 %}
	            		<input type='hidden' name='page' value='item'> 
	             		<td><input type="submit" name="vote" value="like" id = 'like' disabled=True></td>
	            	{% else %}
	            		<input type='hidden' name='page' value='item'> 
	             		<td><input type="submit" name="vote" value="like"></td>
	           		{% endif %}

	           		{% if voto.voto == -1 %}
	           			<input type='hidden' name='page' value='item'> 
	            		<td><input type="submit" name="vote" value="dislike" id ='dislike' disabled=True></td>
	            	{% else %}
	            		<input type='hidden' name='page' value='item'> 
	              		<td><input type="submit" name="vote" value="dislike"></td>
	            	{% endif %}
            	</li>
          	</form>

          	<form method="POST" enctype="multipart/form-data" action="/alimentadores/{{item.alimentador}}/{{item.id}}" id="imagen">
          		{% csrf_token %}
          		<li>{% trans "Comente" %}
          			{{ form.as_p }}
					<input type="submit" value ='{% trans "Enviar" %}'>
            	</li>
          	</form>
        {% endif %}

        <br><b>{% trans "Comentarios" %}</b>
        	{% if comentarios %}
	        	{% for comentario in comentarios %}
	        		<div id = "cajacomentario">
	        			<br>{{ comentario.user }} {% trans "comentó el" %} {{ comentario.fecha }}
	        			<br>{{ comentario.titulo }}
	        			<br>{{ comentario.comentario }}
	        			{% if comentario.imagen %}
	        				<br><img src="{{ comentario.imagen.url }}" width="100" height="100"><br>
	        			{% endif %}
	        		</div>
				{% endfor %}
			{% else %}
				<br>{% trans "Sé el primero en comentar algo" %}
			{% endif %}
	</li>
{% endblock %}

ProyectoFinal/miscosas/templates/registro.html
{% load static %}
{% load i18n %}
<link rel="shortcut icon" type="image/png" href={% static "favicon.ico" %}/>
<h2>{% trans "Registrarse como un nuevo usuario" %}</h2>

<form method="POST">
	{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{% trans "Registrar" %}</button>
</form>

<a href="/login">{% trans "Inicie sesión" %}</a>

ProyectoFinal/miscosas/templates/upload.html
{% extends "base.html" %}
{% load i18n %}

{% block imagen %}
<div id="cambiarimagen">

    <h1>{% trans "Suba una imagen" %}</h1> 
    <form  method="POST" enctype= "multipart/form-data" action="" id="imagen"> 
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value ='{% trans "Enviar" %}'>
    </form>
 </div>

{% endblock %}

ProyectoFinal/miscosas/templates/usuarios.html
{% extends "base.html" %}
{% load i18n %}

{% block users %}
	
	<h2>{% trans "Usuarios registrados" %}</h2>
	{% for imagen in imagenes %}
		<h1>{{ imagen.user.username }}</h1> 
		<img src="{{ imagen.imagen.url }}" width="100" height="100"><br>
		<ul>
        	<li><a href="/usuarios/{{ imagen.user.username }}">{% trans "perfil" %}</a></li>
        </ul>
        {% trans "Items votados" %}: {{ imagen.user.voto_set.count }}
        <br>{% trans "Comentarios realizados" %}: {{ imagen.user.comentario_set.count }}<br>

	{% endfor %}

{% endblock %}